parameters:
  ivariable.extra.user.class: iVariable\ExtraBundle\Service\User
  ivariable.extra.repo.class: iVariable\ExtraBundle\Service\Repository\Repository

services:
  iv.user:
    class: %ivariable.extra.user.class%
    arguments:
      context: "@security.context"

  em:
    alias: doctrine.orm.default_entity_manager

  ivariable.extra.templating.helper.options:
    class: iVariable\ExtraBundle\Twig\Extension\Options
    arguments: [ "@service_container" ]
    tags:
       - { name: twig.extension, alias: options }